services:
  - type: web
    name: gym-management-backend
    runtime: java
    repo: https://github.com/im-sovanny-cell/gym.management
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
    plan: free
